services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${username}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${password}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URI}
    env_file:
      - .env